name: Deploy to Huggingface

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Buat file .env dari .env.example dan isi nilai environment
      - name: Create .env file
        run: |
          cp .env.example .env
          echo "DB_HOST=localhost" >> .env
          echo "DB_USER=postgres" >> .env
          echo "DB_PASSWORD=12345" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_NAME=quzuu_db_dev" >> .env
          echo "SALT=@quzuuAp12025" >> .env

      # Setup Docker
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t quzuu-api-dev:latest .

      # Push to Huggingface
      - name: Push to Huggingface
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          echo "Deploying to Huggingface..."
          docker login -u username -p $HF_TOKEN docker.pkg.github.com
          docker tag quzuu-api-dev:latest huggingface.co/spaces/lifedebugger/quzuu-api-dev:latest
          docker push huggingface.co/spaces/lifedebugger/quzuu-api-dev:latest
