name: Deploy to Huggingface

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Buat file .env dari .env.example dan isi nilai environment
      - name: Create .env file
        run: |
          cp .env.example .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_USER=postgres" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_NAME=postgres" >> .env
          echo "SALT=@quzuuAp12025" >> .env

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t quzuu-api-dev:latest .

      # Tag the Docker Image for Huggingface
      - name: Tag Docker Image for Huggingface
        run: |
          docker tag quzuu-api-dev:latest huggingface.co/spaces/lifedebugger/quzuu-api-dev:latest

      # Push Docker Image to Huggingface
      - name: Push Docker Image to Huggingface
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          docker login -u $HF_TOKEN -p $HF_TOKEN huggingface.co
          docker push huggingface.co/spaces/lifedebugger/quzuu-api-dev:latest

      # Verify Deployment
      - name: Verify Deployment
        run: |
          echo "Deployment completed. Your Huggingface Space is now updated."
