name: Deploy to Huggingface

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Docker
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t my-golang-api:latest .

      # Push to Huggingface
      - name: Push to Huggingface
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          echo "Deploying to Huggingface..."
          docker login -u username -p $HF_TOKEN docker.pkg.github.com
          docker tag my-golang-api:latest huggingface.co/spaces/lifedebugger/quzuu-api-dev:latest
          docker push huggingface.co/spaces/lifedebugger/quzuu-api-dev:latest
