name: Deploy to Huggingface

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Buat file .env dari .env.example dan isi nilai environment
      - name: Create .env file
        run: |
          cp .env.example .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_USER=postgres" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_NAME=postgres" >> .env
          echo "SALT=@quzuuAp12025" >> .env

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t quzuu-api-dev:latest .

      # Tag Docker Image for Huggingface
      - name: Tag Docker Image for Huggingface
        run: |
          docker tag quzuu-api-dev:latest huggingface.co/spaces/lifedebugger/quzuu-api-dev:latest

      # Push Docker Image to Huggingface
      - name: Push Docker Image to Huggingface
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          echo $HF_TOKEN | docker login huggingface.co -u $HF_TOKEN --password-stdin
          docker push huggingface.co/spaces/lifedebugger/quzuu-api-dev:latest
