name: Deploy to Huggingface

on:
  push:
    branches:
      - master

jobs:
  deploy-to-huggingface:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup Git
      - name: Setup Git for Huggingface
        run: |
          git config --global user.email "abdan.hafidz@gmail.com"
          git config --global user.name "abdanhafidz"

      # Clone Huggingface Space Repository
      - name: Clone Huggingface Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git clone https://huggingface.co/spaces/lifedebugger/quzuu-api-dev space
          cd space
          git remote set-url origin https://$HF_TOKEN@huggingface.co/spaces/lifedebugger/quzuu-api-dev

      # Copy Files to Huggingface Space
      - name: Copy Files to Space
        run: |
          rsync -av --exclude='.git' ./ space/

      # Commit and Push to Huggingface Space
      - name: Commit and Push to Huggingface
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd space
          git add .
          git commit -m "Deploy files from GitHub repository"
          git push origin main
