name: Deploy to Huggingface

on:
  push:
    branches:
      - master

jobs:
  deploy-to-huggingface:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Git
      - name: Setup Git for Huggingface
        run: |
          git config --global user.email "abdan.hafidz@gmail.com"
          git config --global user.name "abdanhafidz"

      # Clone Huggingface Space Repository
      - name: Clone Huggingface Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git clone https://huggingface.co/spaces/lifedebugger/quzuu-api-dev space
          cd space
          git remote set-url origin https://huggingface.co/spaces/lifedebugger/quzuu-api-dev

      # Copy Files to Huggingface Repository
      - name: Copy Files
        run: |
          cp -r ./* space/
          cp -r ./.env space/ # Optional, jika perlu menyertakan file .env
          cd space
          git add .
          git status # Untuk memastikan file ditambahkan

      # Commit and Push to Huggingface
      - name: Commit and Push Changes
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd space
          git commit -m "Update application files"
          git push https://huggingface.co/spaces/lifedebugger/quzuu-api-dev
